image: registry.choerodon.com.cn/tools/cibase:0.5.0

stages:
  - build

chart-build:
  stage: build
  script: 
    - chart_build

.auto_devops: &auto_devops |
  curl -o .auto_devops.sh \
      "${CHOERODON_URL}/devops/ci?token=${Token}"
  if [ $? -ne 0 ];then
    cat .auto_devops.sh
    exit 1
  fi
  source .auto_devops.sh

before_script:
  - *auto_devops